Add ref finance example
subquery/near-subql-starter pull request #9
Opened 2023-11-15 21:36 UTC by bgodlin

2023-11-15 22:20 UTC, deverka approved these changes

2023-11-20 21:56 UTC, deverka commented
@jamesbayly please take a look

2023-11-27 04:35 UTC, jamesbayly requested changes

2023-11-27 04:35 UTC, jamesbayly commented on Near/near-ref-finance/README.md
> +# SubQuery - Example Project for NEAR
```suggestion
# SubQuery - Example Project for Ref Finance on NEAR
```

2023-11-27 04:35 UTC, jamesbayly commented on Near/near-ref-finance/docker-compose.yml
> +      - --batch-size=1
```suggestion
```

Don't commit this kind of `batch-size`

2023-11-27 04:35 UTC, jamesbayly commented on Near/near-ref-finance/project.ts
> +    // chainId is the EVM Chain ID, for Near Aurora this is 1313161554
This looks incorrect?

2023-11-27 04:35 UTC, jamesbayly commented on Near/near-ref-finance/src/mappings/mappingHandlers.ts
> +  // An Action can belong to either a transaction or a receipt
I think it's good practice to keep a logger event here to clearly show to people that "this is working"
```suggestion
  logger.info(`Swap found at block ${action.transaction.block_height}`);
  // An Action can belong to either a transaction or a receipt
```

2023-11-27 04:35 UTC, jamesbayly commented on Near/near-ref-finance/src/mappings/mappingHandlers.ts
> +    logger.warn("Swap is saved");
```suggestion
    logger.info("Swap is saved");
```

2023-11-27 04:35 UTC, jamesbayly commented on Near/near-ref-finance/src/mappings/mappingHandlers.ts
> +export async function getOrCreateToken(tokenid: string): Promise<Token> {
do these need to be exported?

2023-11-27 04:35 UTC, jamesbayly commented on Near/near-ref-finance/src/mappings/mappingHandlers.ts
> +export async function getOrCreatePool(poolid: string): Promise<Pool> {
Same here?

2023-11-27 11:14 UTC, bgodlin commented on Near/near-ref-finance/project.ts
> +    // chainId is the EVM Chain ID, for Near Aurora this is 1313161554
Resolved in https://github.com/subquery/near-subql-starter/pull/9/commits/17daedf84833222b353afcf060f7fdbe8381d373

2023-11-27 11:14 UTC, bgodlin commented on Near/near-ref-finance/src/mappings/mappingHandlers.ts
> +export async function getOrCreateToken(tokenid: string): Promise<Token> {
Resolved as part of https://github.com/subquery/near-subql-starter/pull/9/commits/8432ad594fbf8bb2155396748cd1179fd74f59e5

2023-11-27 11:15 UTC, bgodlin commented on Near/near-ref-finance/src/mappings/mappingHandlers.ts
> +export async function getOrCreatePool(poolid: string): Promise<Pool> {
Resolved as part of https://github.com/subquery/near-subql-starter/commit/8432ad594fbf8bb2155396748cd1179fd74f59e5

2023-11-27 11:18 UTC, merged